CREATE TABLE CINEMA(
	ID_CINEMA NUMBER NOT NULL,
	NOME VARCHAR2(200) NOT NULL,
	ESTADO VARCHAR2(200) NOT NULL,
	CIDADE VARCHAR2(200) NOT NULL,
	PRIMARY KEY(ID_CINEMA)
);

CREATE TABLE FILME(
	ID_FILME NUMBER NOT NULL,
	NOME VARCHAR2(200) NOT NULL,
	IDIOMA VARCHAR2(200) NOT NULL,
	CLASSIFICACAO NUMBER NOT NULL,
	DURACAO NUMBER NOT NULL,
	PRIMARY KEY(ID_FILME)
);

CREATE TABLE CLIENTE(
	ID_CLIENTE NUMBER NOT NULL,
	PRIMEIRO_NOME VARCHAR2(200) NOT NULL,
	ULTIMO_NOME VARCHAR2(200) NOT NULL,
	CPF VARCHAR2(11) UNIQUE NOT NULL,
	IDADE NUMBER NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE INGRESSO(
	ID_INGRESSO NUMBER NOT NULL,
	ID_FILME NUMBER NOT NULL,
	ID_CLIENTE NUMBER NOT NULL,
	ID_CINEMA NUMBER NOT NULL,
	VALOR NUMBER NOT NULL,
	CADEIRA NUMBER NOT NULL,
	DATA_HORA TIMESTAMP NOT NULL,
	DISPONIBLIDADE CHAR NOT NULL,
	CONSTRAINT FK_INGRESSO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_INGRESSO_FILME FOREIGN KEY (ID_FILME) REFERENCES FILME(ID_FILME),
	CONSTRAINT FK_INGRESSO_CINEMA FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(ID_CINEMA),
	PRIMARY KEY(ID_INGRESSO)
);

CREATE SEQUENCE SEQ_ID_CLIENTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_CINEMA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_FILME
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ID_INGRESSO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO CINEMA (ID_CINEMA, NOME, ESTADO, CIDADE)
VALUES (SEQ_ID_CINEMA.nextval, 'GNC', 'RIO GRANDE DO SUL', 'PORTO ALEGRE' );

INSERT INTO FILME (ID_FILME, NOME, IDIOMA, CLASSIFICACAO, DURACAO)
VALUES (SEQ_ID_FILME.nextval, 'HOMEM ARANHA: SEM VOLTA PRA CASA ', 'DUBLADO', 12, 157);

INSERT INTO CLIENTE (ID_CLIENTE, PRIMEIRO_NOME, ULTIMO_NOME, CPF, IDADE, EMAIL)
VALUES (SEQ_ID_CLIENTE.nextval, 'MARCO', 'VAN BASTEN', '99999999999', 45, 'MARCO@DBC.COM')

INSERT INTO INGRESSO (ID_INGRESSO,ID_CINEMA, ID_FILME, ID_CLIENTE, VALOR, CADEIRA, DATA_HORA, DISPONIBLIDADE)
VALUES (SEQ_ID_INGRESSO.nextval,1,1,1,15, 05, TO_DATE('21/10/22 21:30','dd-mm-yy hh24:mi'), 'S')

ALTER TABLE CINE_DEV.CLIENTE RENAME COLUMN IDADE TO DATA_NASCIMENTO;
ALTER TABLE CINE_DEV.CLIENTE MODIFY DATA_NASCIMENTO DATE;

INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'Halloween Ends', 'LEGENDADO', 18, 111);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'Morte, Morte, Morte', 'DUBLADO', 16, 95);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'As Aventuras de Tadeo e a Tábua de Esmeralda', 'LEGENDADO', 0, 90);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'Os Suburbanos - O Filme', 'DUBLADO', 14, 85);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'Órfã 2: A Origem', 'LEGENDADO', 16, 98);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'Minions 2: A Origem de Gru', 'DUBLADO', 0, 94);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'A Liga dos Superpets', 'LEGENDADO', 0, 106);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'Ingresso Para o Paraíso', 'DUBLADO', 12, 102);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'A Mulher Rei', 'LEGENDADO', 14, 134);
INSERT INTO FILME VALUES (SEQ_ID_FILME.nextval, 'Adão Negro', 'DUBLADO', 14, 125);

INSERT INTO CINEMA VALUES (SEQ_ID_CINEMA.nextval, 'GNC Iguatemi', 'RS', 'Porto Alegre');
INSERT INTO CINEMA VALUES (SEQ_ID_CINEMA.nextval, 'Cinemark Barra Sul', 'RS', 'Porto Alegre');
INSERT INTO CINEMA VALUES (SEQ_ID_CINEMA.nextval, 'Cinemark Wallig', 'RS', 'Porto Alegre');
INSERT INTO CINEMA VALUES (SEQ_ID_CINEMA.nextval, 'UCI ParkShopping Canoas', 'RS', 'Porto Alegre');
INSERT INTO CINEMA VALUES (SEQ_ID_CINEMA.nextval, 'Cinemark Canoas', 'RS', 'Porto Alegre');
INSERT INTO CINEMA VALUES (SEQ_ID_CINEMA.nextval, 'Centerplex Caruaru', 'PE', 'Caruaru');
INSERT INTO CINEMA VALUES (SEQ_ID_CINEMA.nextval, 'Cinepolis Patteo Olinda', 'PE', 'Olinda');

INSERT INTO	CLIENTE VALUES	(SEQ_ID_CLIENTE.nextval, 'Vinicius', 'Assunção', '31816219002', TO_DATE('22/06/1999','dd-mm-yyyy'), 'vinicius-assuncao90@nine9.com.br');
INSERT INTO	CLIENTE VALUES	(SEQ_ID_CLIENTE.nextval, 'Filipe', 'Nascimento', '82766295470', TO_DATE('05/06/1995','dd-mm-yyyy'), 'filipe.isaac.nascimento@djapan.com.br');
INSERT INTO	CLIENTE VALUES	(SEQ_ID_CLIENTE.nextval, 'Isabella',  'Vieira', '81863960988', TO_DATE('09/07/1976','dd-mm-yyyy'), 'isabella_vieira@dc4.com.br');
INSERT INTO	CLIENTE VALUES	(SEQ_ID_CLIENTE.nextval, 'Nina', 'Freitas', '98827209514', TO_DATE('16/03/1951','dd-mm-yyyy'), 'nina.fernanda.freitas@arosacampinas.com.br');
INSERT INTO	CLIENTE VALUES	(SEQ_ID_CLIENTE.nextval, 'Fátima', 'Rosa', '40407480692', TO_DATE('06/10/1996','dd-mm-yyyy'), 'fatima-darosa74@skyzepp.com');
INSERT INTO	CLIENTE VALUES	(SEQ_ID_CLIENTE.nextval, 'Nicolas', 'Silveira', '10601608119', TO_DATE('03/05/1992','dd-mm-yyyy'), 'nicolas-silveira87@vasconcelosdias.com');
INSERT INTO	CLIENTE VALUES	(SEQ_ID_CLIENTE.nextval, 'Nair', 'Sales', '52700584058', TO_DATE('03/05/1992','dd-mm-yyyy'), 'nairmalusales@bravo.com.br');

ALTER TABLE CINE_DEV.INGRESSO MODIFY ID_CLIENTE NUMBER NULL;
ALTER TABLE CINE_DEV.INGRESSO MODIFY CADEIRA NUMBER NULL;

INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBLIDADE) 
VALUES (SEQ_ID_INGRESSO.nextval, 1, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBLIDADE) 
VALUES (SEQ_ID_INGRESSO.nextval, 1, 2, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBLIDADE) 
VALUES (SEQ_ID_INGRESSO.nextval, 2, 1, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S');
INSERT INTO INGRESSO (ID_INGRESSO, ID_FILME, ID_CINEMA, VALOR, DATA_HORA, DISPONIBLIDADE) 
VALUES (SEQ_ID_INGRESSO.nextval, 2, 4, 30, TO_DATE('21/10/2022 21:30','dd-mm-yyyy hh24:mi'), 'S');